{% set version = "1.3.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-gridpattern
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/gridpattern_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gridpattern/gridpattern_{{ version }}.tar.gz
  sha256: 2e67ff7c4e381a4ce60fbc368d1fd01917503a970f3179641501ccbb7d8acea5

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-glue
    - r-memoise
    - r-png
    - r-rlang
    - r-sf
  run:
    - r-base
    - r-glue
    - r-memoise
    - r-png
    - r-rlang
    - r-sf

test:
  commands:
    - $R -e "library('gridpattern')"           # [not win]
    - "\"%R%\" -e \"library('gridpattern')\""  # [win]

about:
  home: https://trevorldavis.com/R/gridpattern/, https://github.com/trevorld/gridpattern
  license: MIT
  summary: Provides 'grid' grobs that fill in a user-defined area with various patterns.  Includes enhanced versions of the geometric and image-based patterns originally contained in the 'ggpattern' package as well as original 'pch', 'polygon_tiling', 'regular_polygon', 'rose', 'text', 'wave', and 'weave' patterns plus support
    for custom user-defined patterns.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
